### PR TITLE
Update to latest version of Django 3.2 (#65)

### LINKED ISSUE #65: Upgrade to Django 3.2
Since there have been a few 3.2 Django releases (`3.2.4` is the latest), we can upgrade to 3.2 instead of continuing to update for `3.1.x` patch releases.

This should also make unnecessary the `dependabot` PR incorporating the `3.1.x` security patches.

### PR DESCRIPTION
**Pull request by ssciolla**
This PR updates the Django version to the latest `3.2` release (`3.2.5`). Locally I did not see any issues during the image build, when running the test suite, or doing a test run with the test API Directory instance. The PR aims to resolve #65.

Resource(s):
- https://docs.djangoproject.com/en/3.2/releases/3.2/

### CODE REVIEW

**Comment by pushyamig** [comment]
I did pull the PR and ran locally, I still have old `.env` since initial release, so probably the assignment submission list is big and the process was still running. But this proves kind off the Django update has no issue.

I ran the test with the command `docker-compose run -e TEST_MODE=True job` and they all came clear.

I think this change is OK.

**Comment by ssciolla** [comment]
> I did pull the PR and ran locally, I still have old `.env` since initial release, so probably the assignment submission list is big and the process was still running. But this proves kind off the Django update has no issue.

Thanks, @pushyamig. Whenever you do a test run of the main application, I recommend updating `fixtures.json` to use `default_time_filter` for each exam that are more recent, so you don't have to wait a long time for it to finish or hit the APIs too much.

**Comment by pushyamig** [comment]
>  I recommend updating fixtures.json to use default_time_filters for each exam that are more recent, 

I did that and was able to send all the submission with out errors.

At the end you send the email and that's where I saw error `OSError: [Errno 99] Cannot assign requested address`, Probably this is ok since I don't have email server locally?

**Comment by ssciolla** [comment]
> At the end you send the email and that's where I saw error `OSError: [Errno 99] Cannot assign requested address`, Probably this is ok since I don't have email server locally?

Yeah, this is described here: https://github.com/tl-its-umich-edu/placement-exams#sending-email. If you're running locally, I would pretty much always use `EMAIL_DEBUG=1` (which is the default).

**Review by pushyamig — APPROVED** [review]
Works fine with django update

**Pull request merged**
