### PR TITLE
Fix handling of multiple submissions from one student for a single exam (#27)

### PR DESCRIPTION
**Pull request by ssciolla**
This PR makes changes to the `Submission` model and `ScoresOrchestration` to properly handle what I've been calling in shorthand "duplicates": the case where the a single user has multiple submissions for the same exam. It turns out that when a student has multiple submissions to the same assignment, the `id` field doesn't change; instead an `attempt` field is incremented. The PR introduces an `attempt_num` field that in combination with `submission_id` can be enforced as unique (before there was a unique constraint on `submission_id` alone, leading to database insertion errors during testing). `ScoresOrchestration` was updated to pull the `attempt` value from the Canvas submission object and insert it as `attempt_num` in the database. Unit tests and fixtures have been updated to reflect these changes. The PR aims to resolve issue #27.

### CODE REVIEW

**Comment by pushyamig** [comment]
If you end up in getting 2 submission from a student for the same exam, It will end up as a separate row in DB and are you sending both score to Mpathways during the report?

**Comment by ssciolla** [comment]
> If you end up in getting 2 submission from a student for the same exam, It will end up as a separate row in DB and are you sending both score to Mpathways during the report?

Yes, they will both be sent to M-Pathways. I think this is the desired behavior. If the registrar approves a re-take, we don't want there to be any manual intervention on our side to allow that. If the registrar hasn't approved a re-take for some reason, I still think we want to send all the scores and have a record in our database; I think (but am not positive) it would get flagged as an issue on the M-Pathways side.

**Comment by pushyamig** [comment]
Yes, regardless of what's the decision about the retake exam between student and registrar our job is send all the score that got submitted.

**Comment by ssciolla** [comment]
Thanks for the review! I did some additional testing with Cathy; everything is working well. I'm going to merge now. We'll plan some more end-to-end tests with this soon.

**Pull request merged**
